# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CommandLineDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  platform :osx, '10.10'

  # Pods for CommandLineDemo

  pod 'CommandLine', :path => '..', :subspecs => ['Command']

end
